name: Sign Firefox Extension：123pan Json Share

on:
  workflow_dispatch:
jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' # 或者您项目需要的 Node.js 版本

    - name: Install web-ext
      run: npm install -g web-ext

    - name: Build and Sign Extension
      run: web-ext sign --source-dir ./123panjson --api-key ${{ secrets.AMO_ISSUER }} --api-secret ${{ secrets.AMO_SECRET }} --artifacts-dir ./web-ext-artifacts
      env:
        WEB_EXT_API_KEY: ${{ secrets.AMO_ISSUER }}
        WEB_EXT_API_SECRET: ${{ secrets.AMO_SECRET }}

    - name: 123pan Json Share
      uses: actions/upload-artifact@v4
      with:
        name: firefox-extension
        path: ./web-ext-artifacts/*.xpi # 上传签名后的 .xpi 文件
